version: "3"
services:
  democracy-tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - 18081:8080
    environment:
      CATALINA_OPTS: "-Djava.net.preferIPv4Stack=true -Djava.awt.headless=true"
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom -Xmx1g -Xms1g"
      TZ: Asia/Seoul
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./static:/var/www
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./tomcat/ROOT.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml:ro
      - ./tomcat/webapps:/usr/local/tomcat/webapps
  democracy-nginx:
    image: nginx:1.15.7
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
      - ./tomcat/webapps/ROOT:/usr/share/nginx/tomcat:ro
    links:
      - democracy-tomcat