-- 태그
CREATE TABLE `TB_ISSUE_TAG` (
	`TAG_ID`           BIGINT(20) UNSIGNED NOT NULL COMMENT '태그ID', -- 태그ID
	`TAG_NAME`         VARCHAR(300)        NOT NULL COMMENT '태그명' -- 태그명
)
COMMENT '태그';

-- 태그
ALTER TABLE `TB_ISSUE_TAG`
	ADD CONSTRAINT `PK_TB_ISSUE_TAG` -- 태그 Primary key
		PRIMARY KEY (
			`TAG_ID` -- 태그ID
		);

ALTER TABLE `TB_ISSUE_TAG`
	MODIFY COLUMN `TAG_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '이슈ID';

-- 태그 Unique Index
CREATE UNIQUE INDEX `UIX_TB_ISSUE_TAG`
	ON `TB_ISSUE_TAG` (
		`TAG_NAME` ASC    -- 태그이름
	);

-- 태깅
CREATE TABLE `TB_ISSUE_TAGGING` (
	`ISSUE_ID`         BIGINT(20) UNSIGNED NOT NULL COMMENT '이슈ID', -- 이슈ID
	`TAG_ID`           BIGINT(20) UNSIGNED NOT NULL COMMENT '태그ID'  -- 태그ID
)
COMMENT '태그';

-- 태깅 Unique Index
CREATE UNIQUE INDEX `UIX_TB_ISSUE_TAGGING`
	ON `TB_ISSUE_TAGGING` (
		`ISSUE_ID` ASC, -- 이슈ID
		`TAG_ID` ASC    -- 태그ID
	);